package notify

import (
	"bytes"
	"crypto/ecdh"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"math/big"
	"strings"
	"testing"
)

func TestV3GroupKey(t *testing.T) {
	creator, err := ecdh.P256().NewPrivateKey(bytes.Repeat([]byte{3}, 32))
	if err != nil {
		t.Fatal(err)
	}
	group, err := ecdh.P256().NewPrivateKey(bytes.Repeat([]byte{4}, 32))
	if err != nil {
		t.Fatal(err)
	}
	creatorKey, err := deriveGroupKey(creator, encode(group.PublicKey().Bytes()), 3, "session-id", "group-id", 1_789_999_000_001)
	if err != nil {
		t.Fatal(err)
	}
	groupKey, err := deriveGroupKey(group, encode(creator.PublicKey().Bytes()), 3, "session-id", "group-id", 1_789_999_000_001)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(creatorKey, groupKey) {
		t.Fatal("ECDH peers derived different session keys")
	}
	if _, err := deriveGroupKey(group, encode(creator.PublicKey().Bytes()), 3, "session-id", "group-id", 1_789_999_000_002); err != nil {
		t.Fatal(err)
	}
}

func TestECDHEncryptionRoundTrip(t *testing.T) {
	creator, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	deviceGroup, err := ecdh.P256().NewPrivateKey(bytes.Repeat([]byte{6}, 32))
	if err != nil {
		t.Fatal(err)
	}
	creatorKey, err := deriveGroupKey(creator, encode(deviceGroup.PublicKey().Bytes()), 3, "session-id", "group-id", 42)
	if err != nil {
		t.Fatal(err)
	}
	deviceGroupKey, err := deriveGroupKey(deviceGroup, encode(creator.PublicKey().Bytes()), 3, "session-id", "group-id", 42)
	if err != nil {
		t.Fatal(err)
	}
	want := decryptedResponse{ID: "response-id", Type: "response", RequestID: "request-id", OptionID: "option-id"}
	nonce, ciphertext, err := encryptJSON(creatorKey, "authenticated-context", want)
	if err != nil {
		t.Fatal(err)
	}
	var got decryptedResponse
	if err := decryptJSON(deviceGroupKey, "authenticated-context", nonce, ciphertext, &got); err != nil {
		t.Fatal(err)
	}
	if got.ID != want.ID || got.Type != want.Type || got.RequestID != want.RequestID || got.OptionID != want.OptionID {
		t.Fatalf("decrypted response = %+v", got)
	}
	if err := decryptJSON(deviceGroupKey, "different-context", nonce, ciphertext, &got); err == nil {
		t.Fatal("decryptJSON accepted ciphertext under different additional data")
	}
}

func TestCryptoKitKeyAgreementKeyCanSignForGoVerifier(t *testing.T) {
	// Generated by CryptoKit from a P256.KeyAgreement.PrivateKey converted to
	// P256.Signing.PrivateKey through its 32-byte raw representation.
	const publicKey = "BBELNDb1e29mRPegyT2CwQTRDYecatngHTz7v3fMdhw7_QSbhJxDhIMf2ou01qolE8YBCF5G8P2rzaUYUU6Mgn8"
	const signature = "0VXCv7Hu45n-46vY7meze8V0XpJ4pyEV54Kl7pTKWDXL1Q_bvityPaHDboBnQGn0y4j0laZLKytakD_-iWuGvw"
	if err := verifyP256Signature(publicKey, signature, "test"); err != nil {
		t.Fatal(err)
	}
}

func TestV3PairingProofAuthentication(t *testing.T) {
	authSecret, err := randomValue(32)
	if err != nil {
		t.Fatal(err)
	}
	secret, err := decode(authSecret)
	if err != nil {
		t.Fatal(err)
	}
	mac := hmac.New(sha256.New, secret)
	fmt.Fprint(mac, "v3\nsession\npairing\ngroup\n42\npublic-key")
	proof := encode(mac.Sum(nil))
	if err := verifyPairingProof(authSecret, 3, "session", "pairing", "group", 42, "public-key", "", proof); err != nil {
		t.Fatal(err)
	}
	if err := verifyPairingProof(authSecret, 3, "session", "pairing", "group", 43, "public-key", "", proof); err == nil {
		t.Fatal("proof was accepted for another key timestamp")
	}
}

func TestV4AttachmentKeyAndAADAreContextBound(t *testing.T) {
	creator, err := ecdh.P256().NewPrivateKey(bytes.Repeat([]byte{7}, 32))
	if err != nil {
		t.Fatal(err)
	}
	group, err := ecdh.P256().NewPrivateKey(bytes.Repeat([]byte{8}, 32))
	if err != nil {
		t.Fatal(err)
	}
	creatorKey, err := deriveAttachmentKey(creator, encode(group.PublicKey().Bytes()), "session", "group", "response", "attachment", 42)
	if err != nil {
		t.Fatal(err)
	}
	groupKey, err := deriveAttachmentKey(group, encode(creator.PublicKey().Bytes()), "session", "group", "response", "attachment", 42)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(creatorKey, groupKey) {
		t.Fatal("ECDH peers derived different attachment keys")
	}
	aead, err := newAEAD(groupKey)
	if err != nil {
		t.Fatal(err)
	}
	nonce := bytes.Repeat([]byte{9}, aead.NonceSize())
	plaintext := []byte{0xff, 0xd8, 0xff, 0xd9}
	aad := attachmentAAD("session", "group", "response", "attachment", 42)
	ciphertext := aead.Seal(nil, nonce, plaintext, []byte(aad))
	got, err := decryptAttachment(creatorKey, aad, encode(nonce), ciphertext)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, plaintext) {
		t.Fatalf("decrypted attachment = %x, want %x", got, plaintext)
	}
	if _, err := decryptAttachment(creatorKey, attachmentAAD("session", "group", "response", "other", 42), encode(nonce), ciphertext); err == nil {
		t.Fatal("attachment decrypted under another attachment ID")
	}
}

func TestV4TransitionChainRejectsInjectionModificationAndRollback(t *testing.T) {
	actorKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	groupKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	member := transitionMember{
		DeviceID: "device", SigningPublicKey: encode(elliptic.Marshal(elliptic.P256(), actorKey.X, actorKey.Y)),
		EncryptionPublicKey: encode(elliptic.Marshal(elliptic.P256(), actorKey.X, actorKey.Y)),
	}
	first := signedGroupTransition{
		TransitionID: "first", PreviousHash: fmt.Sprintf("%064d", 0), Timestamp: 10,
		ActorDeviceID: "device", PublicKey: encode(elliptic.Marshal(elliptic.P256(), groupKey.X, groupKey.Y)),
		Recreated: true, Members: []transitionMember{member},
		PackageDigests: []transitionPackageDigest{{DeviceID: "device", SHA256: fmt.Sprintf("%064d", 1)}},
	}
	firstTranscript := groupTransitionTranscript("group", first)
	first.ActorSignature = signRawP256(t, actorKey, firstTranscript)
	first.ContinuitySignature = signRawP256(t, groupKey, firstTranscript)
	first.TransitionHash = groupTransitionHash("group", first)
	second := signedGroupTransition{
		TransitionID: "second", PreviousHash: first.TransitionHash, Timestamp: 11,
		ActorDeviceID: "device", PublicKey: first.PublicKey, Recreated: false,
		Members:        []transitionMember{member},
		PackageDigests: []transitionPackageDigest{{DeviceID: "device", SHA256: fmt.Sprintf("%064d", 2)}},
	}
	transcript := groupTransitionTranscript("group", second)
	second.ActorSignature = signRawP256(t, actorKey, transcript)
	second.ContinuitySignature = signRawP256(t, groupKey, transcript)
	second.TransitionHash = groupTransitionHash("group", second)
	if _, err := validateV4Transitions("group", []signedGroupTransition{first, second}, 10, first.PublicKey, first.TransitionHash, first.TransitionHash); err != nil {
		t.Fatal(err)
	}

	injected := second
	injected.ContinuitySignature = signRawP256(t, actorKey, transcript)
	injected.TransitionHash = groupTransitionHash("group", injected)
	if _, err := validateV4Transitions("group", []signedGroupTransition{first, injected}, 10, first.PublicKey, first.TransitionHash, first.TransitionHash); err == nil {
		t.Fatal("relay-injected key passed continuity verification")
	}
	modified := second
	modified.Members = []transitionMember{{DeviceID: "changed", SigningPublicKey: member.SigningPublicKey, EncryptionPublicKey: member.EncryptionPublicKey}}
	if _, err := validateV4Transitions("group", []signedGroupTransition{first, modified}, 10, first.PublicKey, first.TransitionHash, first.TransitionHash); err == nil {
		t.Fatal("modified membership passed transition hash verification")
	}
	if _, err := validateV4Transitions("group", []signedGroupTransition{first}, 10, first.PublicKey, first.TransitionHash, second.TransitionHash); err == nil {
		t.Fatal("rollback omitted the previously trusted transition without detection")
	}
}

func TestV4TransitionChainAcceptsAuthenticatedNonGenesisPairingAnchor(t *testing.T) {
	actorKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	previousGroupKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	currentGroupKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	public := func(key *ecdsa.PrivateKey) string {
		return encode(elliptic.Marshal(elliptic.P256(), key.X, key.Y))
	}
	member := transitionMember{
		DeviceID: "device", SigningPublicKey: public(actorKey), EncryptionPublicKey: public(actorKey),
	}
	anchor := signedGroupTransition{
		TransitionID: "pairing-anchor", PreviousHash: strings.Repeat("a", 64), Timestamp: 42,
		ActorDeviceID: member.DeviceID, PublicKey: public(currentGroupKey), Recreated: true,
		Members:        []transitionMember{member},
		PackageDigests: []transitionPackageDigest{{DeviceID: member.DeviceID, SHA256: strings.Repeat("b", 64)}},
	}
	transcript := groupTransitionTranscript("group", anchor)
	anchor.ActorSignature = signRawP256(t, actorKey, transcript)
	anchor.ContinuitySignature = signRawP256(t, previousGroupKey, transcript)
	anchor.TransitionHash = groupTransitionHash("group", anchor)

	if _, err := validateV4Transitions(
		"group", []signedGroupTransition{anchor}, anchor.Timestamp,
		anchor.PublicKey, anchor.TransitionHash, anchor.TransitionHash,
	); err != nil {
		t.Fatalf("authenticated non-genesis pairing anchor was rejected: %v", err)
	}
}

func TestV4TransitionRejectsRecreatedSelfRemovalAndCanonicalizesSignatureHash(t *testing.T) {
	leavingKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	remainingKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	groupKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	attackerKnownKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	member := func(id string, key *ecdsa.PrivateKey) transitionMember {
		public := encode(elliptic.Marshal(elliptic.P256(), key.X, key.Y))
		return transitionMember{DeviceID: id, SigningPublicKey: public, EncryptionPublicKey: public}
	}
	leaving := member("leaving", leavingKey)
	remaining := member("remaining", remainingKey)
	first := signedGroupTransition{
		TransitionID: "first", PreviousHash: strings.Repeat("0", 64), Timestamp: 10,
		ActorDeviceID: leaving.DeviceID, PublicKey: encode(elliptic.Marshal(elliptic.P256(), groupKey.X, groupKey.Y)),
		Recreated: true, Members: []transitionMember{leaving, remaining},
		PackageDigests: []transitionPackageDigest{{DeviceID: leaving.DeviceID, SHA256: strings.Repeat("1", 64)}, {DeviceID: remaining.DeviceID, SHA256: strings.Repeat("2", 64)}},
	}
	transcript := groupTransitionTranscript("group", first)
	first.ActorSignature = signRawP256(t, leavingKey, transcript)
	first.ContinuitySignature = signRawP256(t, groupKey, transcript)
	first.TransitionHash = groupTransitionHash("group", first)

	malleated := first
	raw, err := decode(first.ActorSignature)
	if err != nil {
		t.Fatal(err)
	}
	s := new(big.Int).SetBytes(raw[32:])
	new(big.Int).Sub(new(big.Int).Set(elliptic.P256().Params().N), s).FillBytes(raw[32:])
	malleated.ActorSignature = encode(raw)
	if groupTransitionHash("group", malleated) != first.TransitionHash {
		t.Fatal("signature malleation changed the canonical transition hash")
	}
	if _, err := validateV4Transitions("group", []signedGroupTransition{malleated}, 10, first.PublicKey, first.TransitionHash, first.TransitionHash); err != nil {
		t.Fatalf("malleated but valid signature changed transition identity: %v", err)
	}

	forged := signedGroupTransition{
		TransitionID: "forged", PreviousHash: first.TransitionHash, Timestamp: 11,
		ActorDeviceID: leaving.DeviceID,
		PublicKey:     encode(elliptic.Marshal(elliptic.P256(), attackerKnownKey.X, attackerKnownKey.Y)),
		Recreated:     true, Members: []transitionMember{remaining},
		PackageDigests: []transitionPackageDigest{{DeviceID: remaining.DeviceID, SHA256: strings.Repeat("3", 64)}},
	}
	transcript = groupTransitionTranscript("group", forged)
	forged.ActorSignature = signRawP256(t, leavingKey, transcript)
	forged.ContinuitySignature = signRawP256(t, groupKey, transcript)
	forged.TransitionHash = groupTransitionHash("group", forged)
	if _, err := validateV4Transitions("group", []signedGroupTransition{first, forged}, 10, first.PublicKey, first.TransitionHash, first.TransitionHash); err == nil {
		t.Fatal("recreated self-removal was accepted")
	}
}

func signRawP256(t *testing.T, key *ecdsa.PrivateKey, transcript string) string {
	t.Helper()
	digest := sha256.Sum256([]byte(transcript))
	r, s, err := ecdsa.Sign(rand.Reader, key, digest[:])
	if err != nil {
		t.Fatal(err)
	}
	value := make([]byte, 64)
	r.FillBytes(value[:32])
	s.FillBytes(value[32:])
	return encode(value)
}
